platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!

  # Firebase
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseMessaging'
  pod 'FirebaseAnalytics'

  # Razorpay
  pod 'razorpay-pod', '~> 1.3.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end

